version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev 
    ports: 
      - "3000:3000"
    volumes: 
      - /landing/node_modules
      - .:/langing 
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/landing
    command: ["npm", "run", "test"]